
// Pack URLs for lazy loading
const packUrls = {
    "cpython": "./packages/cpython.pack.br",
    "emscripten": "./packages/emscripten.pack.br",
    "emscripten_docs": "./packages/emscripten_docs.pack.br",
    "emscripten_media": "./packages/emscripten_media.pack.br",
    "emscripten_node_modules": "./packages/emscripten_node_modules.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libGL.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libGL.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libal.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libal.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libc++-noexcept.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libc++-noexcept.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libc++.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libc++.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libc++abi-debug-noexcept.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libc++abi-debug-noexcept.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libc++abi-debug.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libc++abi-debug.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libc++abi-noexcept.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libc++abi-noexcept.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libc++abi.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libc++abi.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libc-debug.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libc-debug.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libc.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libc.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libcompiler_rt.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libcompiler_rt.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libdlmalloc.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libdlmalloc.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libhtml5.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libhtml5.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libnoexit.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libnoexit.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libsockets.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libsockets.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libstubs-debug.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libstubs-debug.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libstubs.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libstubs.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_libz.a": "./packages/emscripten_sysroot_lib_wasm32-emscripten_libz.a.pack.br",
    "emscripten_sysroot_lib_wasm32-emscripten_lto": "./packages/emscripten_sysroot_lib_wasm32-emscripten_lto.pack.br",
    "emscripten_system_include": "./packages/emscripten_system_include.pack.br",
    "emscripten_system_include_GL": "./packages/emscripten_system_include_GL.pack.br",
    "emscripten_system_include_SDL": "./packages/emscripten_system_include_SDL.pack.br",
    "emscripten_system_include_compat": "./packages/emscripten_system_include_compat.pack.br",
    "emscripten_system_lib": "./packages/emscripten_system_lib.pack.br",
    "emscripten_system_lib_compiler-rt_lib": "./packages/emscripten_system_lib_compiler-rt_lib.pack.br",
    "emscripten_system_lib_compiler-rt_lib_sanitizer_common": "./packages/emscripten_system_lib_compiler-rt_lib_sanitizer_common.pack.br",
    "emscripten_system_lib_libc_musl_src": "./packages/emscripten_system_lib_libc_musl_src.pack.br",
    "emscripten_system_lib_libcxx_include": "./packages/emscripten_system_lib_libcxx_include.pack.br",
    "emscripten_system_lib_libcxx_src": "./packages/emscripten_system_lib_libcxx_src.pack.br",
    "emscripten_third_party": "./packages/emscripten_third_party.pack.br",
    "wasm": "./packages/wasm.pack.br",
};

export default packUrls;